spring:
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 10000
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: banking
    password: banking_password
    driver-class-name: org.postgresql.Driver