spring:
  application:
    name: server
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO
    com.redmath: INFO
    org.springframework.security: INFO
  file:
    path: logs